version: '3.8'

services:
  server:
    container_name: anomalous-space-rpg
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    restart: always
   
    environment:
      - NODE_ENV=development
    volumes:
      - ../../:/app/anomalousspace
    ports:
      - '4000:4000'